### PR TITLE
ENH: Re-architect so top-level strategy invokes model invokes dataset

### LINKED ISSUE #3: Build toy case: dataset, model, and strategy
Implement a toy instance of each of a dataset, model, and strategy.  Making this use case work will prioritize ALBench development and will also serve as a regression test.

## Subtasks
- [x] #5
- [x] #6 
- [x] #7
- [x] #14

### PR DESCRIPTION
**Pull request by Leengit**
Also:
    ENH: Implement dumb toy example
    ENH: Add handler base classes and add virtual methods for abstract classes
    TEST: Separate tests into smaller modules
    DOC: Add comments for many methods
    ENH: Add classes AbstractScoringMetric, AbstractDiversityMetric
    ENH: Implement TensorFlowModelHandler train and predict methods

Closes #3

### CODE REVIEW

**Comment by andinet** [comment]
The requirements file is missing. It is hard to figure out all the dependencies required for the project

**Comment by Leengit** [comment]
> The requirements file is missing. It is hard to figure out all the dependencies required for the project

There is `pyprojects.toml` file at the top-level.  It specifies the requirements `h5py` and `numpy` in a format recognized by PyPI, so that once we release versions to PyPI, those who type `pip install al_bench` will get those dependencies too.  I'll add an issue to make this project installable using PyPI.

`tensorflow` is not currently listed as a dependency because the user may have a preference between `tensorflow-cpu` and `tensorflow-gpu`.  Any thoughts on how to make this kind of flexibility for `tensorflow` as user friendly as possible?

**Comment by Leengit** [comment]
It looks like for recent versions, `tensorflow` includes both `tensorflow-gpu` and `tensorflow-cpu`.  That makes things easier.  I'll add `tensorflow` as a dependency.

**Comment by Leengit** [comment]
Issue #19 and Pull Request #20 were submitted for the purpose of using GitHub actions to publish to PyPI, and include adding `tensorflow` as a dependency in `pyproject.toml`.

**Comment by Leengit** [comment]
The force-push just now is to rebase to the current `main` branch.

**Pull request merged**
